# Generated by Django 4.0.6 on 2022-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('billbook', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=10)),
                ('name', models.TextField(max_length=225)),
                ('number', models.TextField(max_length=50)),
                ('vechilename', models.TextField(max_length=100)),
                ('phonenumber', models.TextField(max_length=100)),
                ('type', models.TextField(max_length=225)),
                ('fine', models.TextField(max_length=10)),
            ],
            options={
                'db_table': 'cheat',
            },
        ),
    ]
