# Generated by Django 4.0.6 on 2022-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatmodel',
            name='vechiletype',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
