# Generated by Django 4.0.6 on 2022-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0003_remove_cheatmodel_vechiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatmodel',
            name='licence',
            field=models.CharField(max_length=50),
        ),
    ]
