# Generated by Django 4.0.6 on 2022-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0004_alter_cheatmodel_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('vechiletype', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('color', models.TextField(max_length=225)),
                ('number', models.TextField(max_length=50)),
                ('vechilename', models.TextField(max_length=100)),
                ('phonenumber', models.TextField(max_length=100)),
                ('enginenumber', models.TextField(max_length=225)),
                ('date', models.TextField(max_length=50)),
                ('resolved', models.TextField(blank=True, default='reported', max_length=10)),
            ],
            options={
                'db_table': 'lost',
            },
        ),
    ]
