# Generated by Django 4.0.6 on 2022-07-17 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=55)),
                ('contact', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('medals', models.CharField(blank=True, default='0', max_length=50)),
                ('solvedcases', models.CharField(blank=True, default='0', max_length=50)),
                ('badge', models.CharField(blank=True, default='0', max_length=50)),
                ('cheat', models.CharField(blank=True, default='0', max_length=55)),
                ('product_image', models.FileField(blank=True, upload_to='static/image/user')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
