# Generated by Django 4.0.6 on 2022-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_product_image_userinfomodel_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='badges',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='badge',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='uid',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
